### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by stansu** [troopy28/OptiX-Denoiser-for-Blender#1]
![img_20181119_113746](https://user-images.githubusercontent.com/9460236/48685091-8ec84200-ebef-11e8-991c-8276adcc996c.jpg)

**Comment by troopy28** [comment]
Could you please provide some details? When does this happen?

**Comment by stansu** [comment]
> Could you please provide some details? When does this happen?

It happen when I pressed denoise render.

**Comment by troopy28** [comment]
Which OS are you using? And does this happen every time? 
It seems that the script is not able to use the denoiser's executable (which is supposed to be in the zip file you can download). Did you download the zip file or did you only downloaded the Python file?

**Comment by stansu** [comment]
> Which OS are you using? And does this happen every time?
> It seems that the script is not able to use the denoiser's executable (which is supposed to be in the zip file you can download). Did you download the zip file or did you only downloaded the Python file?

I'm using win7 and win 10.
I download your zip file from your Google drive.
still error.
Thanks for your reply.

**Comment by troopy28** [comment]
What version of blender are you using? And also, did you installed the whole zip file or extracted the python file from it? For the second option won't work, you need to install the whole zip file.

**Comment by stansu** [comment]
> What version of blender are you using? And also, did you installed the whole zip file or extracted the python file from it? For the second option won't work, you need to install the whole zip file.

1. i'm using 2.79
2. i installed whole zip

**Comment by troopy28** [comment]
Well... Hard to know what causes he problem. That _might_ be an elevation problem. Maybe Blender is not allowed to access the file. Does the error occurs when you launch Blender with administrator privileges?
Also, did you make sure the executable exists?
From what I see in the logs, the _script_ is located at ".../2.79/scripts/addons/blender_optix_denoiser.py". This means that the _executable_ should be located at ".../2.79/scripts/addons/Denosier_v2.1/Denoiser.exe". Also, I don't know why your plugin has been installed there, since mines are not installed on the Blender folder, but in "%appdata%/Blender Foundation/Blender/2.79/scripts/addons/[HERE]". 
Could you please:

1. Check if the denoiser executable exists (the first path I've written)
2. If it exists, try to copy the "Denoiser_v2.1" folder in "%appdata%/Blender Foundation/Blender/2.79/scripts/addons/[HERE]". This way, maybe Blender will find it.

Thanks

**Comment by stansu** [comment]
> Well... Hard to know what causes he problem. That _might_ be an elevation problem. Maybe Blender is not allowed to access the file. Does the error occurs when you launch Blender with administrator privileges?
> Also, did you make sure the executable exists?
> From what I see in the logs, the _script_ is located at ".../2.79/scripts/addons/blender_optix_denoiser.py". This means that the _executable_ should be located at ".../2.79/scripts/addons/Denosier_v2.1/Denoiser.exe". Also, I don't know why your plugin has been installed there, since mines are not installed on the Blender folder, but in "%appdata%/Blender Foundation/Blender/2.79/scripts/addons/[HERE]".
> Could you please:
> 
>     1. Check if the denoiser executable exists (the first path I've written)
> 
>     2. If it exists, try to copy the "Denoiser_v2.1" folder in "%appdata%/Blender Foundation/Blender/2.79/scripts/addons/[HERE]". This way, maybe Blender will find it.
> 
> 
> Thanks

Thank you, I will copy denoiser_v2.1 to addons and let you know the result.

**Comment by troopy28** [comment]
So, does it work now?

**Comment by stansu** [comment]
> So, does it work now?

Haven't got time to try it, sorry for your waiting.

**Comment by stansu** [comment]
i copy denoiser_v2.1 to addons.
when i pressed denoise render result, blender will freeze.

**Comment by troopy28** [comment]
Well, as I said in the description of the addon, denoising the render result freezes blender during the denoising. The freezing is not supposed to last. It usually freezes like 10-15 seconds the first time you use the denoiser in the session, and then it takes between 5 and 10 seconds.

**Comment by stansu** [comment]
> Well, as I said in the description of the addon, denoising the render result freezes blender during the denoising. The freezing is not supposed to last. It usually freezes like 10-15 seconds the first time you use the denoiser in the session, and then it takes between 5 and 10 seconds.

I try Denise.exe directly, it's working.
Seems I have to use command line to denoising, thanks anyway!
