### ISSUE TITLE
Move the denoiser in the View Layer panel.

### ISSUE THREAD

**Issue by Harvester62** [troopy28/OptiX-Denoiser-for-Blender#4]
This is not a bug report but mainly an organizational purpose change. Since the standard denoiser in Blender, as well as other denoisers I use, are all placed inside the View Layer properties panel, I would suggest to move the OptiX Denoiser there too, changing the line 234 in __init__.py from

bl_context = "render"
to
bl_context = "view_layer"

Regards.

**Comment by troopy28** [comment]
Hello. 

Most denoisers are in the "View layer" tab mainly because they provide _options_ that are used during rendering. On the other hand, this addon provides _actions_ that can be done, and I think their place is in the rendering panel, next to the usual rendering actions.

Regards
